[package]
name = "nen"
version = "0.0.1"
description = "Nen compiler command-line interface."

[dependencies]
nenc = { path = "crates/nenc" }
nenc_interpreter = { path = "crates/nenc_interpreter" }

[workspace]
members = [ "crates/nenc", "crates/nenc_interpreter" ]
